### ISSUE TITLE
Impossible de bootstraper l'annuaire

### ISSUE THREAD

**Issue by leucos** [laclasse-com/service-annuaire#66]
Impossible de boostrapper l'annauaire.  On se tape une erreur de clefs de suite (et environ 50 warnings de redéfinition de constantes).

Depuis master 15c2796:

```
$ bundle exec rake db:bootstrap
failed: [stack0-int.v3.laclasse.lan] => {"changed": true, "cmd": "cd ~erasme/laclasse-annuaire/; bash -lc 'RACK_ENV=production bundle exec rake db:bootstrap'", "delta": "0:00:01.375654", "end": "2015-07-21 15:50:53.573508", "rc": 1, "start": "2015-07-21 15:50:52.197854", "warnings": []}
...
/home/erasme/bundler_shared/ruby/2.2.0/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
rake aborted!
mismatched number of left keys: [:profil_id, :user_id, :etablissement_id] vs [:id]
/home/erasme/bundler_shared/ruby/2.2.0/gems/sequel-4.14.0/lib/sequel/model/associations.rb:1757:in `def_many_to_many'
/home/erasme/bundler_shared/ruby/2.2.0/gems/sequel-4.14.0/lib/sequel/model/associations.rb:1636:in `associate'
$
```

**Comment by Pilooz** [comment]
Fixed with PR #65
